"""The extract and canonicalize steps send exactly the calls they sent before their split loops moved.

The expected values were generated by running origin/main's extract.py and canonicalize.py (the
in-module loops) with the same stub on the same inputs: a batch of six where the third item makes
the model's reply unusable, once as a truncation and once as garbage JSON. Each call is pinned as
(sha256 prefix of the prompt bytes, max_tokens, items in the prompt); the smallest prompt is pinned
in full so the shape is visible. No API calls.
"""

from __future__ import annotations

import hashlib
import json

import pytest

from patientpunk._utils import LLMResponseError
from pipeline import canonicalize as canon
from pipeline import extract
from prompts.intervention_config import CANONICALIZE_COMPOUND_PROMPT, EXTRACT_PROMPT


def _stub(bad_marker: str, failure: str, calls: list):
    def fake(client, prompt, model=None, system=None, max_tokens=None):
        calls.append((prompt, model, system, max_tokens))
        if bad_marker in prompt:
            if failure == "truncate":
                raise LLMResponseError("response truncated at max_tokens")
            return "garbage"
        if "--- " in prompt:
            return json.dumps([["ldn"]] * prompt.count("--- "))
        names = json.loads(prompt.split("canonicalize:\n")[1])
        return json.dumps({names[0]: f"canonical_{names[0]}"})
    return fake


def _digest(calls: list, count) -> list[tuple[str, int, int]]:
    return [(hashlib.sha256(p.encode()).hexdigest()[:16], mt, count(p)) for p, _m, _s, mt in calls]


EXTRACT_CALLS = [  # (prompt sha256 prefix, max_tokens, texts in the prompt), from origin/main
    ("485078066374dcdf", 1500, 6),
    ("6d40543e776230e4", 750, 3),
    ("0a1dc380d6eca120", 250, 1),
    ("009cc7eec6945997", 500, 2),   # depth 2: gives up, t1 and t2 get []
    ("a8344c781cdd9ed0", 750, 3),
]
CANON_CALLS = [  # (prompt sha256 prefix, max_tokens, names in the prompt), from origin/main
    ("a4050231d3bf5a1f", 2000, 6),
    ("fe10cc4aec72fae7", 2000, 3),
    ("aef9e47316db98b0", 2000, 1),
    ("8862b9c4cfaaebc4", 2000, 2),
    ("1f67309b94d015e3", 2000, 1),
    ("ba58a5178e3f8644", 2000, 1),   # drug2 alone still fails: kept raw, counted
    ("af8aa35ea2002a9b", 2000, 3),
]


@pytest.mark.parametrize("failure", ["truncate", "garbage"])
def test_extract_sends_the_same_calls_as_before_the_move(monkeypatch: pytest.MonkeyPatch, failure: str) -> None:
    calls: list = []
    monkeypatch.setattr(extract, "llm_call", _stub("t2", failure, calls))

    result = extract.extract_batch(None, [f"t{i}" for i in range(6)])

    assert result == [["ldn"], [], [], ["ldn"], ["ldn"], ["ldn"]]
    assert _digest(calls, lambda p: p.count("--- ")) == EXTRACT_CALLS
    assert all(m is extract.MODEL_FAST and s is None for _p, m, s, _mt in calls)
    assert min((p for p, *_ in calls), key=len) == EXTRACT_PROMPT + "\n--- 1 ---\nt0\n\n"


@pytest.mark.parametrize("failure", ["truncate", "garbage"])
def test_canonicalize_sends_the_same_calls_as_before_the_move(monkeypatch: pytest.MonkeyPatch, failure: str) -> None:
    calls: list = []
    monkeypatch.setattr(canon, "llm_call", _stub('"drug2"', failure, calls))

    result = canon.canonicalize_batch(None, [f"drug{i}" for i in range(6)])

    assert result.mapping == {
        "drug0": "canonical_drug0", "drug1": "canonical_drug1", "drug2": "drug2",
        "drug3": "canonical_drug3", "drug4": "drug4", "drug5": "drug5",
    }
    assert (result.failed_names, result.split_names) == (1, 6)
    assert _digest(calls, lambda p: len(json.loads(p.split("canonicalize:\n")[1]))) == CANON_CALLS
    assert all(m is canon.MODEL_STRONG and s is None for _p, m, s, _mt in calls)
    assert min((p for p, *_ in calls), key=len) == CANONICALIZE_COMPOUND_PROMPT + '\n\nDrug names to canonicalize:\n["drug0"]'
